name: Update ICS File

on:
  schedule:
    - cron: "0 0 * * *" # 매일 자정에 실행
  workflow_dispatch:

jobs:
  update-ics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21" # 최신 LTS 버전으로 업데이트 권장
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Generate ICS File
        run: node index.js # ICS 파일을 생성하는 명령어

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_ENV

      - name: Commit and push if changes
        if: env.changes == 'true'
        run: |
          git config --global user.email "kadragon@knue.ac.kr"
          git config --global user.name "kangdonguk"
          git add -A
          git commit -m "Automatically update ICS file"
          git push
