name: Update Gist

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # 매일 자정에 실행
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate Result
        run: node index.js > events.ics

      - name: Update Gist
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          GIST_ID=936ee41f20486d76a70b79a7163041ef
          FILENAME=events.ics
          CONTENT=$(<events.ics)
          JSON=$(jq -n \
                  --arg content "$CONTENT" \
                  '{description: "An updated gist description", files: { "events.ics": {content: $content}}}')
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/gists/$GIST_ID \
          -d "$JSON"
